Kartverket.Metadatakatalog/Models/Api/Metadata.cs
using Kartverket.Metadatakatalog.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Caching;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Xml;
using Kartverket.Metadatakatalog.Helpers;
using Kartverket.Metadatakatalog.Models.Translations;
using Resources;

namespace Kartverket.Metadatakatalog.Models.Api
{
    public class Metadata
    {
        /// <summary>
        /// The uniqueidentifier
        /// </summary>
        public string Uuid { get; set; }
        /// <summary>
        /// The title
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// The abstract
        /// </summary>
        public string @Abstract { get; set; }
        /// <summary>
        /// The type of metadata
        /// </summary>
        public string Type { get; set; }
        /// <summary>
        /// The type of metadata translated
        /// </summary>
        public string TypeTranslated { get; set; }
        /// <summary>
        /// The grouping name of dataset series
        /// </summary>
        public string TypeName { get; set; }
        /// <summary>
        /// The theme
        /// </summary>
        public string Theme { get; set; }
        /// <summary>
        /// The owner of the metadata
        /// </summary>
        public string Organization { get; set; }
        /// <summary>
        /// The list of owners of the metadata
        /// </summary>
        public List<string> Organizations { get; set; }
        /// <summary>
        /// The logo for the organization
        /// </summary>
        public string OrganizationLogo { get; set; }
        /// <summary>
        /// Illustrative image of the metadata
        /// </summary>
        public string ThumbnailUrl { get; set; }
        /// <summary>
        /// Url for downloading dataset/service
        /// </summary>
        public string DistributionUrl { get; set; }
        /// <summary>
        /// The protocol used for downloading
        /// </summary>
        public string DistributionProtocol { get; set; }
        /// <summary>
        /// Url to metadata details page
        /// </summary>
        public string ShowDetailsUrl { get; set; }
        /// <summary>
        /// Url to metadata owner organization details page
        /// </summary>
        public string OrganizationUrl { get; set; }
        /// <summary>
        /// The layer for services
        /// </summary>
        public string DistributionName { get; set; }
        /// <summary>
        /// True if one of the nationalinitiativs(Samarbeid og lover) is "Åpne data"
        /// </summary>
        public bool? IsOpenData { get; set; }
        public bool? AccessIsOpendata { get; set; }
        public bool AccessIsRestricted { get; set; }
        public bool AccessIsProtected { get; set; }
        /// <summary>
        /// <summary>
        /// True if one of the nationalinitiativs(Samarbeid og lover) is "Det offentlige kartgrunnlaget"
        /// </summary>
        public bool? IsDokData { get; set; }
        /// <summary>
        /// Url for legend/drawing rules
        /// </summary>
        public string LegendDescriptionUrl { get; set; }
        /// <summary>
        /// Url for productsheet
        /// </summary>
        public string ProductSheetUrl { get; set; }
        /// <summary>
        /// Url for detailed spesifications
        /// </summary>
        public string ProductSpecificationUrl { get; set; }
        /// <summary>
        /// Services for dataset
        /// </summary>
        public List<string> DatasetServices { get; set; }
        /// <summary>
        /// Distributions for dataset
        /// </summary>
        public List<string> Distributions { get; set; }
        /// <summary>
        /// Services for dataset with ShowMapLink true
        /// </summary>
        public List<DatasetService> DatasetServicesWithShowMapLink { get; set; }
        /// <summary>
        ///  Datasets for service
        /// </summary>
        public List<string> ServiceDatasets { get; set; }
        /// <summary>
        /// Bundles for dataset
        /// </summary>
        public List<string> Bundles { get; set; }
        /// <summary>
        /// ServiceLayers
        /// </summary>
        public List<string> ServiceLayers { get; set; }
        /// <summary>
        /// Datasets in series
        /// </summary>
        public List<Dataset> SerieDatasets { get; set; }
        /// <summary>
        /// Serie for datasett
        /// </summary>
        public Serie Serie { get; set; }
        /// <summary>
        /// AccessConstraint
        /// </summary>
        public string AccessConstraint { get; set; }
        /// <summary>
        /// OtherConstraintsAccess
        /// </summary>
        public string OtherConstraintsAccess { get; set; }
        /// <summary>
        /// DataAccess
        /// </summary>
        public string DataAccess { get; set; }
        /// <summary>
        /// Url for service mapped to dataset (wms)
        /// </summary>
        public string ServiceDistributionUrlForDataset { get; set; }
        public string ServiceUuid { get; set; }

        /// <summary>
        /// Url for service mapped to dataset (wfs)
        /// </summary>
        public string ServiceWfsDistributionUrlForDataset { get; set; }

        /// <summary>
        /// DistributionType
        /// </summary>
        //public string DistributionType { get; set; } 
        public string DistributionType { get; set; }
        /// <summary>
        /// URL for Get Capabilities
        /// </summary>
        public string GetCapabilitiesUrl { get; set; }

        /// <summary>
        /// The full dataset name
        /// </summary>
        public string DatasetName { get; set; }

        public DateTime? Date { get; set; }
        private string MapUrl { get; set; }
        public bool? ShowMapLink { get; set; }
        private bool ShowServiceMapLink { get; set; }
        private string DownloadUrl { get; set; }
        private string ServiceUrl { get; set; }
        public string SpatialScope { get; set; }


        public Metadata() { 
        }
        public Metadata(SearchResultItem item, UrlHelper urlHelper)
        {
            Uuid = item.Uuid;
            Title = item.Title;
            Abstract = item.Abstract;
            Type = item.Type;
            TypeName = item.TypeName;
            TypeTranslated = TranslateType();
            Theme = item.Theme;
            Organization = item.Organization;
            Organizations = item.Organizations;

            OrganizationLogo = item.OrganizationLogoUrl;
            ThumbnailUrl = item.ThumbnailUrl;
            DistributionUrl = item.DistributionUrl;
            DistributionProtocol = item.DistributionProtocol;
            DistributionName = item.DistributionName;
            DistributionType = item.DistributionType;
            GetCapabilitiesUrl = GetGetCapabilitiesUrl(item);

            ShowDetailsUrl = WebConfigurationManager.AppSettings["KartkatalogenUrl"] + "metadata/uuid/" + item.Uuid;
            OrganizationUrl = WebConfigurationManager.AppSettings["KartkatalogenUrl"] + "?organizations=" + item?.Organization;

            if (item.DataAccess != null && item.DataAccess == "Åpne data" && UI.OpenData == "Open data")
                item.DataAccess = "Open data";

            if (item.NationalInitiative != null && item.NationalInitiative.Contains(UI.OpenData)
                || (!string.IsNullOrEmpty(item.DataAccess) && (item.DataAccess == UI.OpenData
                || item.DataAccess.Contains("ingen begrensninger") || item.DataAccess.Contains("no limitations"))))
                IsOpenData = true;
            else IsOpenData = false;

            AccessIsOpendata = IsOpenData;
            AccessIsRestricted = SimpleMetadataUtil.IsRestricted(item.OtherConstraintsAccess);
            AccessIsProtected = SimpleMetadataUtil.IsProtected(item.AccessConstraint); 

            if (item.NationalInitiative != null && item.NationalInitiative.Contains("Det offentlige kartgrunnlaget"))
                IsDokData = true;
            else IsDokData = false;


            LegendDescriptionUrl = item.LegendDescriptionUrl;
            ProductSheetUrl = item.ProductSheetUrl;
            ProductSpecificationUrl = item.ProductSpecificationUrl;
            DatasetServices = item.DatasetServices;
            DatasetServicesWithShowMapLink = AddDatasetServicesWithShowMapLink(DatasetServices);
            ServiceDatasets = item.ServiceDatasets;
            Distributions = item.Distributions;
            Bundles = item.Bundles;
            ServiceLayers = item.ServiceLayers;
            AccessConstraint = item.AccessConstraint;
            OtherConstraintsAccess = item.OtherConstraintsAccess;
            DataAccess = item.DataAccess;
            ServiceDistributionUrlForDataset = item.ServiceDistributionUrlForDataset;
            ServiceUuid = item.ServiceDistributionUuidForDataset;
            ServiceWfsDistributionUrlForDataset = item.ServiceWfsDistributionUrlForDataset != null ? item.ServiceWfsDistributionUrlForDataset : WfsServiceUrl();
            Date = item.Date;
            DatasetName = item.DatasetName;

            if (Type == "dataset" || Type == "series")
            {
                if (!string.IsNullOrWhiteSpace(item.ServiceDistributionProtocolForDataset))
                {
                    string commonPart = SimpleMetadataUtil.GetCommonPartOfNorgeskartUrl(item.ServiceDistributionProtocolForDataset, true);

                    if (item.ServiceDistributionProtocolForDataset.Contains(SimpleMetadataUtil.OgcWms))
                    {
                        if (!string.IsNullOrWhiteSpace(item.ServiceDistributionUrlForDataset))
                        {
                            ServiceUrl = $"{commonPart}{RemoveQueryString(item.ServiceDistributionUrlForDataset)}";

Kartverket.Metadatakatalog/Controllers/MetadataController.cs
using System;
using System.Web.Mvc;
using Kartverket.Metadatakatalog.Models;
using Kartverket.Metadatakatalog.Models.ViewModels;
using Kartverket.Metadatakatalog.Service;
using Kartverket.Metadatakatalog.Service.Application;
using System.Linq;
using Kartverket.Metadatakatalog.Service.Search;

namespace Kartverket.Metadatakatalog.Controllers
{
    [HandleError]
    public class MetadataController : Controller
    {
        private static readonly log4net.ILog Log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private readonly IMetadataService _metadataService;
        private readonly ISearchService _searchService;

        public MetadataController(IMetadataService metadataService, ISearchService searchService)
        {
            _metadataService = metadataService;
            _searchService = searchService;
        }
        
        /// <summary>
        /// Metadata page. 
        /// </summary>
        /// <param name="uuid"></param>
        /// <param name="organization"></param>
        /// <param name="title"></param>
        /// <param name="orderby"></param>
        /// <returns>/metadata/{organization}/{title}/{uuid}</returns>
        public ActionResult Index(string uuid, string organization = null, string title = null, string orderby = "title")
        {
            MetadataViewModel model = null;
            //try
            //{
                model = _metadataService.GetMetadataViewModelByUuid(uuid);
                model = Sort(model, orderby);
            //}
            //catch (InvalidOperationException exception)
            //{
            //    Log.Error("Metadata with uuid: " + uuid + " not found in Geonetwork.", exception);
            //    //throw new Exception("Metadata with uuid: " + uuid + " not found in Geonetwork.");
            //}
            if (model == null)
            {
                Log.Error("Metadata with uuid: " + uuid + " not found.");
                return new HttpNotFoundResult("Metadata with uuid: " + uuid + " not found in Geonetwork.");
            }

            SeoUrl url = model.CreateSeoUrl();
            if (!url.Matches(organization, title) && !string.IsNullOrWhiteSpace(organization))
                return RedirectToActionPermanent("Index", new { organization = url.Organization, title = url.Title, uuid = uuid });

            return View(model);
            

        }

        private MetadataViewModel Sort(MetadataViewModel model, string orderby)
        {
            
            if (model != null && model.Related != null)
            {
                if (orderby == "title")
                    model.Related = model.Related.OrderBy(o => o.Title).ToList();
                else if(orderby == "title_desc")
                    model.Related = model.Related.OrderByDescending(o => o.Title).ToList();
                else if (orderby == "organization")
                    model.Related = model.Related.OrderBy(o => o.ContactOwner.Organization).ToList();
                else if (orderby == "organization_desc")
                    model.Related = model.Related.OrderByDescending(o => o.ContactOwner.Organization).ToList();
            }

            return model;
        }


        /// <summary>
        /// Shows metadata by selected organization
        /// </summary>
        /// <param name="parameters"></param>
        /// <returns>/etatvis-oversikt/{organization}</returns>
        public ActionResult Organization(SearchByOrganizationParameters parameters)
        {
            parameters.AddDefaultFacetsIfMissing();
            FixOrganizationParameters(parameters);
            SearchResultForOrganization searchResult = _searchService.SearchByOrganization(parameters);
            var model = new SearchByOrganizationViewModel(parameters, searchResult);
            return View(model);
        }


        private static void FixOrganizationParameters(SearchByOrganizationParameters parameters)
        {
            if (parameters.OrganizationSeoName == "organisasjon")
            {
                parameters.OrganizationSeoName = null;
            }
        }

        

        protected override void OnException(ExceptionContext filterContext)
        {
            Log.Error("Error", filterContext.Exception);
        }
    }
}

Kartverket.Metadatakatalog/Views/Metadata/Organization.cshtml
@using Kartverket.Metadatakatalog.Models.ViewModels
@using Kartverket.Metadatakatalog.Helpers
@model SearchByOrganizationViewModel

@{
    ViewBag.Title = Resources.UI.DepartmentalOverviewHeader;
}

@section breadcrumb {
    <li class="active">@Model.OrganizationName</li>
}

<div id="feedback-alert" class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <span class="message"></span>
</div>

<section class="heading">
    <div class="row">
        <div class="col-sm-12">
            <h1 class="small-h1">
                @ViewBag.Title
            </h1>
        </div>
        <div class="col-sm-12">
            <span class="separator-lg"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <form id="organizationDD" action="@Url.Action("Organization", "Metadata", new { OrganizationSeoName = "" })" name="FilterForm" method="get" class="custom-select">
                @Html.DropDownList("OrganizationSeoName", Model.OrganizationSelectList, Resources.UI.SelectOrganization, new { @class = "form-control" })
            </form>
        </div>
    </div>
</section>



@{
    string url = HttpContext.Current.Request.Url.AbsoluteUri;
    if (url.Contains("etatvis-oversikt/organisasjon"))
    {
        url = url.Replace("etatvis-oversikt/organisasjon", "api/datasets");
    }
    else if (url.Contains("etatvis-oversikt"))
    {
        url = url.Replace("etatvis-oversikt/" + Model.OrganizationSeoName, "api/datasets");
    }
    else
    {
        url = url.Replace("metadata/" + Model.OrganizationSeoName, "api/datasets");
    }
    Uri uri = new Uri(url);
    string path = String.Format("{0}{1}{2}{3}", uri.Scheme,
    Uri.SchemeDelimiter, uri.Authority, uri.AbsolutePath);
    var qs = HttpUtility.ParseQueryString("");

    for (int f = 0; f < Model.FacetParameters.Count; f++)
    {
        var facet = Model.FacetParameters[f];

        qs.Add("facets[" + f + "]name", facet.Name);
        qs.Add("facets[" + f + "]value", facet.Value);
    }
    qs.Set("Offset", "1"); qs.Set("limit", Model.NumFound.ToString()); qs.Add("mediatype", "csv");
    string query = qs.ToString(); string urlCSV = path + "?" + query;
}




<div id="vue-container" class="row">


    <script type="text/x-template" id="searchResultTemplate">
        <div>
            <div v-if="$root.viewType == 'tableView' && items.length" class="row resultItemRowTableHeader">
                <div class="col-sm-4" is="header-title"></div>
                <div class="col-sm-2" is="header-type"></div>
                <div class="col-sm-3" is="header-organization"></div>
                <div class="col-sm-1" is="header-open-data"></div>
                <div class="col-sm-1" is="header-map"></div>
                <div class="col-sm-1" is="header-add-to-cart"></div>
            </div>

            <div v-if="$root.viewType == 'tableView'" class="menu-separator"></div>
            <div v-for="item in items" is="resultItem"
                 v-bind:result-item="item"
                 v-bind:selected-fields="[
                 {name: 'title', size: '4'},
                 {name: 'distributionType', size: '2'},
                 {name: 'owner', size: '3'},
                 {name: 'openData', size: '1'}
                 ]"
                 v-bind:selected-buttons="[
                 'showInMapButton',
                 'addToCartButton'
                 ]">
            </div>
            <div class="clearfix"></div>
        </div>
    </script>

    <div class="col-md-9">
        <!-- <div is="facet-filter" filter-type="tabs" class="facet-filter"></div>-->
        @if (Model.Result != null)
        {
            <div is="theme-group"></div>
        }
        <div class="margin-top-10">
            @Html.Partial("_PaginationForOrganization", Model)
        </div>
    </div>
    <div class="col-sm-12 col-md-3 pull-left hidden-sm hidden-xs">
        <aside>
            <h3 class="">@Resources.UI.FilterSearch:</h3>
            <span class="separator-small"></span>
            <div is="facet-filter" filter-type="sidebar" class="facet-filter"></div>
            <h3 class="" style="padding-top: 40px;">@Resources.UI.Pages</h3>
            <span class="separator-small"></span>
            @Html.Partial("_FilterPages")

            <div class="save-as-menu">
                <h3 style="padding-top: 40px;">@Resources.UI.SaveAs:</h3>
                <span class="separator-small"></span>

                <div class="no-padding-bottom save-as-dropdown">
                    <div class="custom-select">
                        <select onchange="additionalView(this.value)" class="form-control">
                            <option value="csvUrl" selected="selected">CSV</option>
                        </select>
                    </div>
                </div>
                <div id="saveButtons" class="no-padding-bottom save-as-buttons">
                    <a class="btn" id="csvUrl" href="@urlCSV">@Resources.UI.Save</a>
                </div>
            </div>
        </aside>
    </div>
</div>



@section scripts {
    @Html.Partial("_ThemeGroup", Model)
    @Html.Partial("_FacetFilter", Model)

    @{ var javaScriptSerializer = new System.Web.Script.Serialization.JavaScriptSerializer(); }

    <script>

        // Setter url for søkeresultat
        @if (Model.OrganizationSeoName != null) {
            @:setMainSearchUrl('etatvis-oversikt/@Model.OrganizationSeoName');
                            @:setMainSearchApiUrl('search?facets[0]name=organization&facets[0]value=@Model.OrganizationName');
                        }
        else
        {
            @:setMainSearchUrl('etatvis-oversikt/organisasjon');
                        }


    </script>

    <script>
        function showAlert(message, colorClass) {
            $('#feedback-alert').attr('class', 'alert alert-dismissible alert-' + colorClass);
            $('#feedback-alert .message').html(message);
            $('#feedback-alert').show();
        }

        $(document).ready(function () {
            $("#OrganizationSeoName").change(
                function () {
                    this.form.submit();
                    location.href = $(this).val();
                }
            );

        });

        $(document).ready(function () {
            @if (Html.DownloadServiceEnabled())
            {
            <text>
            if (localStorage.getItem("orderItems") != null) {
                var storedOrderItems = JSON.parse(localStorage["orderItems"]);
                var orderitemCount = storedOrderItems.length;
                if (orderitemCount > 0) {
                    $('#orderitem-count').text(orderitemCount);
                    $('#orderitem-count-text').text(' datasett');
                    updateAllCartButtons(storedOrderItems);
                } else {
                    $('#orderitem-count').text('');
                    $('#orderitem-count-text').text('Nedlastningen er tom');
                }
            } else {
                $('#orderitem-count').text('');
                $('#orderitem-count-text').text('Nedlastningen er tom');
            }
            </text>
            }
        });
    </script>

    <script>
        var Search = new Vue({
            el: "#vue-container",
            components: {
                ThemeGroup: ThemeGroup,
                FacetFilter: FacetFilter
            },
            data: {
                viewType: 'tableView',
                selectedFields: [
                    { name: 'title', size: '5' },
                    { name: 'owner', size: '4' },
                    { name: 'openData', size: '1' }
                ],
                selectedButtons: [
                    'showInMapButton',
                    'addToCartButton'
                ]
            }
        });
    </script>

}